-- 코드를 입력하세요
SELECT 
A.TITLE,
A.BOARD_ID,
B.REPLY_ID,
A.WRITER_ID,
B.CONTENTS, 
A.CREATED_DATE
from USED_GOODS_BOARD A, USED_GOODS_REPLY B
WHERE TO_CHAR(A.CREATED_DATE, 'yyyy-mm') = '2022-10'
AND A.BOARD_ID = B.BOARD_ID
ORDER BY A.CREATED_DATE, A.TITLE
;