SELECT 
A.TITLE AS "게시글 제목",
A.BOARD_ID AS "게시글 ID",
B.REPLY_ID AS "댓글 ID",
B.WRITER_ID AS "댓글 작성자 ID", -- 이 부분이 틀렸었음
B.CONTENTS AS "댓글 내용", 
TO_CHAR(B.CREATED_DATE, 'YYYY-MM-DD') AS "댓글 작성일"
from USED_GOODS_BOARD A, USED_GOODS_REPLY B
WHERE TO_CHAR(A.CREATED_DATE, 'yyyy-mm') = '2022-10'
AND A.BOARD_ID = B.BOARD_ID
ORDER BY B.CREATED_DATE ASC, A.TITLE ASC
;